MULTIPLY_SIGN = "*"
# MULTIPLY_SIGN = "·"
# POWER_SIGN = "**"
POWER_SIGN = "^"
DIMENSIONLESS_STR = "|"
DEFAULT_ERROR_CALCULATION_TYPE = "MAX_DEVIATION"

DECIMAL_PRECISE = 6

SORT_MEASURES_BY_DIM_POWER = True

DEBUG = False
DETAILED_DEBUG = False
TESTS_DEBUG = False
